name: momento
description: momento app.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^0.12.9+4
  firebase_auth: ^0.14.0+2
  firebase_storage: ^3.0.6
  provider: ^3.1.0
  image_picker: ^0.6.1+4
  rxdart: ^0.22.2
  carousel_slider: ^1.3.1
  flutter_secure_storage: ^3.3.1+1
  flutter_multiselect: ^0.4.0
  flutter_spinkit: ^4.0.0
  cached_network_image: ^1.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
  - assets/images/

  fonts:
    - family: WorkSansSemiBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-SemiBold.ttf

    - family: WorkSansBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Bold.ttf

    - family: WorkSansMedium
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Medium.ttf
